### ISSUE TITLE
Profiles are not shared between characters

### ISSUE THREAD

**Issue by BannZay** [RomanSpector/CompactRaidFrame#21]
We have to setup everything from the scratch for each character we create.

Moreover, there is profiling feature but it does not really work. The profiles are not shared between characters =(

**Comment by RomanSpector** [comment]
Most likely you misunderstood how profiles work

**Comment by RomanSpector** [comment]
Profiles are required to automatically apply settings based on where you are, in a group of two, three people, on the battlefield, in a dungeon, etc.

This is exactly how profiles work on official servers. For each character, you need to configure your profile, because each character has different specializations

**Comment by BannZay** [comment]
questionable blizzards decision... 
Roman, thanks for the explanation.

**Comment by BannZay** [comment]
Retail is a bit different story, but, however, even there you could have multiple characters with very simmillar or same spec

**Comment by BannZay** [comment]
As for me, I truly hate making new characters because I have to setup all adons what is pain if you have a lot of them.
Having profiles reduce the pain, this is why I think that this is essential feature
